In [2]:
import numpy as np
np.random.seed(0)

In [3]:
# .T transpose... changes rows into collumns and vice versa
exampleArray = [[1, 2, 3, 4],
			[7, 5, -1, 9],
			[3, 8, 6, 1]]
print(np.array(exampleArray).T)

[[ 1  7  3]
 [ 2  5  8]
 [ 3 -1  6]
 [ 4  9  1]]


In [4]:
# Single layer
inputs = [[1, 2, 3, 2.5],
			[2.0, 5.0, -1.0, 2.0],
			[-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
			[0.5, -0.91, 0.26, -0.5],
			[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# .T required to avoid shape errors
output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [5]:
# 2 Layers without objects
inputs = [[1, 2, 3, 2.5],
			[2.0, 5.0, -1.0, 2.0],
			[-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
			[0.5, -0.91, 0.26, -0.5],
			[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
			[-0.5, 0.12, -0.33],
			[-0.44, 0.74, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
print(layer2_outputs)


[[ 0.5031  -1.04185 -2.02665]
 [ 0.2434  -2.7332  -5.7814 ]
 [-0.99314  1.41254 -0.34604]]


In [6]:
# How .randn and .zeros work. 
# 0.1 to make values below 1 (standart for neural networks)
print(0.1 * np.random.randn(2, 3))
print()
print(np.zeros((2, 4)))

[[ 0.17640523  0.04001572  0.0978738 ]
 [ 0.22408932  0.1867558  -0.09772779]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Multiple layers using objects. X = inputs
X = [[1, 2, 3, 2.5],
	 [2.0, 5.0, -1.0, 2.0],
	 [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
	def __init__(self, n_inputs, n_neurons):
		self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
		self.biases = np.zeros((1, n_neurons))
	def forward(self, inputs):
		self.output = np.dot(inputs, self.weights) + self.biases

# Layer_Dense(x, y) x = number of elements in list from X (4).
# y can be any value
# If creating another layer, x has to be equal to y from the previous layer.
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
print()
layer2.forward(layer1.output)
print(layer2.output)

[[-0.4400875  -0.11547023 -0.427905   -0.20302835 -0.35402716]
 [-0.2612908  -0.79256919  0.82318568 -0.29964906 -0.25353471]
 [-1.01232311 -0.3436137   0.14667266 -0.16021039 -0.29076763]]

[[0.04339992 0.0555352 ]
 [0.01304788 0.05316297]
 [0.0130678  0.01591002]]
